### ISSUE TITLE
Coding convention

### ISSUE THREAD

**Issue by MarcSeebold** [SpagAachen/Ballz#13]
I suggest to use Microsoft's C# coding convention.
Discuss!

https://msdn.microsoft.com/en-us/library/ms229002%28v=vs.110%29.aspx
https://msdn.microsoft.com/de-de/library/ff926074.aspx

**Comment by LukasBoersma** [comment]
+1 for the standard Microsoft conventions.

Also, we could enforce the conventions by checking them in the automated builds with something like [StyleCop](http://stylecop.codeplex.com/).

**Comment by Martin-Schultz** [comment]
Agreed with the part about Style Cop.

However regarding the MS C# Coding and naming conventions, i think we can use them for orientation, especially as long as they concur with the conventions used by MonoGame.

But i wouldn't be so harsh, as MS Conventions State Comments should stat with Capital letters and end with a dot ... well i dont see the problem if someone messes that up we are not writing an essay, so i would be glad if the grammar fraction would calm down.

I also would not like to dictate when to use var, as i in general do not like var. I would appreciate it if you only used it when the type is obvious but i wouldn't want to force someone to use var in a loop.

As for tabs vs spaces ... yes i do prefer spaces but unfortunately the default configuration of most of my ides is to use tabs.... however do you want to use 4 or 3 spaces? ms says to use 4.

can we discuss the rest next week when we meet in person?

**Comment by krux02** [comment]
Warum schreibt ihr englisch? Ist hier irgendwer der englisch besser kann als deutsch. Ich bin zwar kein Microsoft fan, aber ich würden den Konventionen eine chanse geben. Aber dann bitte unverändert. Also keine kein Änderungen wie 3 Leerzeichen oder so. Und nur `var` also _typinferenz_ zu nutzen ist auch sehr angenehm, vorrausgesetzt man hat einen editor den das nicht verwirrt (sollte in C# wirklich kein problem sein).

Falls diese spezifikation sich an einigen stellen als nicht passend herausstellt, kann man ja immer noch überlegen ob wir es ändern. Aber ich denke ich könnte mich auch an vollständige Sätze mit Punkt und Komma in Kommentaren gewöhnen.
