### ISSUE TITLE
GUI / Menu Decision

### ISSUE THREAD

**Issue by Martin-Schultz** [SpagAachen/Ballz#22]
As Marc wants tons of fancy features for the gui ;)
and really praises CEF, i am thinking about adding cefsharp to our project.

what are your opinions, shall we continue to use our own gui stuff, or take a closer look at cefsharp?

**Comment by krux02** [comment]
For the menue, all we need, are buttons. A button can be implemented with 4 integers, a label and a background color. Everything that is more than that is pulling our attention away from our goal to hava a simple game fast. My principle is KISS keep it simple stupid, and I am clearly against CEF, because we should shift our focus on the game, not the GUI.

**Comment by MarcusVoelker** [comment]
GUI is more than menu, though. And with CEF, we can make a much nicer looking GUI than plain coloured buttons. If Marc, who has experience working with CEF, says it's nice, I'd say let him do it, as soon as he finished his network work.

**Comment by LukasBoersma** [comment]
> Everything that is more than that is pulling our attention away from our goal to hava a simple game fast.

I have to second that. Our current focus should be on gameplay and functionality.

However, I am a big fan of HTML GUIs and CEF in particular. Integrating it is really simple. In fact, I am working on a project that uses CefSharp for the GUI right now. In the long run, I think it's a good idea to use it.

So the real question is: **Do we need more GUI features at this point?** If yes, I'd vote for integrating CEF. But if we can somehow work with the current GUI features, I think it would be wiser to wait with CEF until after the next milestone.

**Comment by MarcSeebold** [comment]
Re-implementing the menu with CEF may take some time.
However, the current menu lacks a lot of features.
One use-case for me would be a multiplayer lobby.
With the current framework that is barely possible.
As a compromise, i suggest to tag this issues as low priority and expand the functionality of the current menu by quick work-arounds and hacks.

**Comment by Martin-Schultz** [comment]
@MarcSeebold what specific features do you need? since we have basic elements like labels which can be used as a button by adding a handler?

i would really like a lightweight layout system for positioning of elements.
