### ISSUE TITLE
advanced networking

### ISSUE THREAD

**Issue by Martin-Schultz** [SpagAachen/Ballz#26]
synchronize the rest of the game via network so that we can actually play via lan or internet.

maybe you want to think of using a protocol class instead of submitting single value types, e.g. using a wrapper class that has a member which holds the type of payload, and a member which is of type object and is the actual payload (or string so you can take more advantage of the serialization / deserialization functions).

**Comment by LukasBoersma** [comment]
Schon fertig, Marc?
