### ISSUE TITLE
Integrate mgcb execution in project configuration

### ISSUE THREAD

**Issue by Martin-Schultz** [SpagAachen/Ballz#8]
Currently the execution of mgcb is done by manually opening the mgcb file with the content pipeline tool and running build in the tool. It would be much more convenient if mgcb was executed by the IDE prior to building the Content project (by setting the outputdirectory flag this could even make the content project obsolete)

whoever wants to have fun with the solution and project files can take this issue and selfassign it.

MGCB documentation
http://www.monogame.net/documentation/?page=MGCB

**Comment by Martin-Schultz** [comment]
since we are already adding the processed .xnb files, do we still need this integration?

**Comment by LukasBoersma** [comment]
Don't think so.

+1 for closing.
